/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-openlst
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_OPENLST_API_H
#define INCLUDED_OPENLST_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_openlst_EXPORTS
#define OPENLST_API __GR_ATTR_EXPORT
#else
#define OPENLST_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_OPENLST_API_H */
